'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ADefault

    '''<summary>
    '''ttl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ttl As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MNUList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MNUList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ManList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''AdminManList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdminManList2 As Global.Pars_TC.AdminManList

    '''<summary>
    '''SBList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SBList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ULList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ULList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UMList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UMList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''URList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents URList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
