'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UsersEdit

    '''<summary>
    '''edituserform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents edituserform As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''euerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents euerror As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ueusername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ueusername As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''uepassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uepassword As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ueexpire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ueexpire As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''uestartdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uestartdate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''uemultilogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uemultilogin As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''uecomment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uecomment As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''uesavesubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uesavesubmit As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
