'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RenameFile

    '''<summary>
    '''renameform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents renameform As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''renameerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents renameerror As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''oldname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oldname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''newname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''editbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editbtn As Global.System.Web.UI.WebControls.ImageButton
End Class
